mysoapp/config/routes.rb
Rails.application.routes.draw do
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create"
  get "signup" => "users#new", :as => "signup"
  get "like/:id" => "entries#like", :as => "like"
  get "unlike/:id" => "entries#unlike", :as => "unlike"
  get "share/:id" => "entries#share", :as => "share"
  get "myfriends" => "relations#index", :as => "myfriends"
  get "sendQuery/:id" => "relations#query", :as => "sendQuery"
  get "accept/:id" => "relations#accept", :as => "accept"
  get "revoke/:id" => "relations#destroy", :as => "revoke"
  get "deny/:id" => "relations#deny", :as => "deny"
  get "users" => "users#index", :as => "users"
  resources :users
  resources :session
  resources :entries
  resources :relations
  root :to => "entries#index"
end

mysoapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>MySoApp</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
    <div id="container">
        <div class="user_nav">
            <% if session[:user] %>
                <div>Logged in as <%= session[:user] %>.</div>
                <div><%= link_to "Init", entries_path %>
                <%= link_to "Relations", myfriends_path %>
                <%= link_to "Users", users_path %>
                <%= link_to "Log out", logout_path %></div>
            <% else %>
                <%= link_to "Sign up", signup_path %> or
                <%= link_to "log in", login_path %>.
            <% end %>
        </div>
        <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
        <%= yield %>
    </div>
</body>
</html>