mysoapp/config/routes.rb
Rails.application.routes.draw do
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create"
  get "signup" => "users#new", :as => "signup"
  get "like/:id" => "entries#like", :as => "like"
  get "unlike/:id" => "entries#unlike", :as => "unlike"
  get "share/:id" => "entries#share", :as => "share"
  get "myfriends" => "relations#index", :as => "myfriends"
  get "sendQuery/:id" => "relations#query", :as => "sendQuery"
  get "accept/:id" => "relations#accept", :as => "accept"
  get "revoke/:id" => "relations#destroy", :as => "revoke"
  get "deny/:id" => "relations#deny", :as => "deny"
  get "users" => "users#index", :as => "users"
  resources :users
  resources :session
  resources :entries
  resources :relations
  root :to => "entries#index"
end

mysoapp/app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :user1, :class_name => "User"
  belongs_to :user2, :class_name => "User"
end

mysoapp/app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_action :set_relation, only: [:show, :edit, :update, :destroy, :accept, :deny]

  # GET /relations
  # GET /relations.json
  def index
    if session[:user] != nil
      if (User.where(name: session[:user]).first).role != 0 
        me = User.where(name: session[:user]).first
        @relations = Relation.where('user1_id = ? OR user2_id = ?', me, me)
      else
        @relations = Relation.all
      end
    end
  end

  # GET /relations/1
  # GET /relations/1.json
  def show
  end

  # GET /relations/new
  def new
    if !session[:user]
      redirect_to relations_path, :alert => "You have to log in to create a new relation"
    else
        @relation = Relation.new
    end
  end

  # GET /relations/1/edit
  def edit
    @relation = relation.find(params[:id])
    if @relation.user1_id.name != @currentUser.name or @currentUser.role != 0
      redirect_to entries_path, :alert => "You cannot edit another user relation!"
    else
      @relation = Relation.find(params[:id])
    end
  end

  # POST /relations
  # POST /relations.json
  def create
    @relation = Relation.new(relation_params)
    name1 = @relation.user1_id
    name2 = @relation.user2_id
    user1 = User.where(name: name1).first
    user2 = User.where(name: name2).first
    @relation = Relation.create(user1_id: user1.id, user2_id: user2.id, status: 0)
    
    respond_to do |format|
      if @relation.save
        format.html { redirect_to @relation, notice: 'Relation was successfully created.' }
        format.json { render :show, status: :created, location: @relation }
      else
        format.html { render :new }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relations/1
  # PATCH/PUT /relations/1.json
  def update
    respond_to do |format|
      if @relation.update(relation_params)
        format.html { redirect_to @relation, notice: 'Relation was successfully updated.' }
        format.json { render :show, status: :ok, location: @relation }
      else
        format.html { render :edit }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relations/1
  # DELETE /relations/1.json
  def destroy
    if @relation.user1_id == @currentUser.id or @currentUser.role == 0
      @relation.destroy
      respond_to do |format|
        format.html { redirect_to relations_url, notice: 'Relation was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to relations_url, notice: 'You cant revoke anothers users queries'
    end
  end
  

  def query
    @relation = Relation.create(user1_id: (User.where(name: session[:user]).first).id, user2_id: params[:id], status: 0)
   
    respond_to do |format|
      if @relation.save
        format.html { redirect_to relations_url, notice: 'Query sent' }
        format.json { render :show, status: :created, location: @relation }
      else
        format.html { render :new }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  def accept

    if @relation.user2_id == @currentUser.id or @currentUser.role == 0
      if @relation.status == 0
        @relation.status = 1
        if @relation.save
          redirect_to relations_url, notice: 'Relation acepted' 
        else
          render :new         
        end
      else
        redirect_to relations_url, notice: 'Relation already acepted'
      end
    else
      redirect_to relations_url, notice: 'You cant accept this relation'
    end
  end 

  def deny
    if @relation.user2_id == @currentUser.id or @currentUser.role == 0
      if @relation.status == 0
        @relation.destroy
        respond_to do |format|
          format.html { redirect_to relations_url, notice: 'Relation was denied.' }
          format.json { head :no_content }
        end
      else
        redirect_to relations_url, notice: 'Relation already acepted'
      end
    else
      redirect_to relations_url, notice: 'You cant deny this relation'
    end
  end 


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relation
      @relation = Relation.find(params[:id])
      @currentUser = User.where(name: session[:user]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relation_params
      params.require(:relation).permit(:user1_id, :user2_id, :status)
    end
end

mysoapp/app/helpers/relations_helper.rb
module RelationsHelper
end

mysoapp/app/views/relations/_form.html.erb
<%= form_for(relation) do |f| %>
  <% if relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(relation.errors.count, "error") %> prohibited this relation from being saved:</h2>

      <ul>
      <% relation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user1_id %>
    <%= f.text_field :user1_id %>
  </div>

  <div class="field">
    <%= f.label :user2_id %>
    <%= f.text_field :user2_id %>
  </div>

  <!--div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div-->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mysoapp/app/views/relations/edit.html.erb
<h1>Editing Relation</h1>

<%= render 'form', relation: @relation %>

<%= link_to 'Show', @relation %> |
<%= link_to 'Back', relations_path %>

mysoapp/app/views/relations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relations</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relations.each do |relation| %>
      <tr>
        <td><%= relation.user1.name %></td>
        <td><%= relation.user2.name %></td>
        <% if relation.status == 0 %>
          <td>Pendiente</td>
        <% else %>
          <td>Aceptada</td>
        <% end %>
        <td><%= link_to 'Accept', accept_path(relation.id) %></td>
        <td><%= link_to 'Deny', deny_path(relation.id) %></td>
        <td><%= link_to 'Revoke', revoke_path(relation.id), data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Show', relation %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

mysoapp/app/views/relations/new.html.erb
<h1>New Relation</h1>

<%= render 'form', relation: @relation %>

<%= link_to 'Back', relations_path %>

mysoapp/app/views/relations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @relation.user1.name %>
</p>

<p>
  <strong>To:</strong>
  <%= @relation.user2.name %>
</p>

<p>
  <strong>Status:</strong>
  <% if @relation.status == 0 %>
    <t>Pendiente</t>
  <% else %>
    <t>Aceptada</t>
  <% end %>
</p>

<%= link_to 'Edit', edit_relation_path(@relation) %> |
<%= link_to 'Back', relations_path %>