mysoapp/config/routes.rb
Rails.application.routes.draw do
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create"
  get "signup" => "users#new", :as => "signup"
  get "like/:id" => "entries#like", :as => "like"
  get "unlike/:id" => "entries#unlike", :as => "unlike"
  get "share/:id" => "entries#share", :as => "share"
  get "myfriends" => "relations#index", :as => "myfriends"
  get "sendQuery/:id" => "relations#query", :as => "sendQuery"
  get "accept/:id" => "relations#accept", :as => "accept"
  get "revoke/:id" => "relations#destroy", :as => "revoke"
  get "deny/:id" => "relations#deny", :as => "deny"
  get "users" => "users#index", :as => "users"
  resources :users
  resources :session
  resources :entries
  resources :relations
  root :to => "entries#index"
end

mysoapp/app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
end

mysoapp/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy, :like, :unlike, :share]

  # GET /entries
  # GET /entries.json
  def index
    if session[:user] != nil
      if (User.where(name: session[:user]).first).role != 0 
        friends = Array.new
        friendships = Relation.where(user1_id: User.where(name: session[:user]).first , status: 1)
        if friendships != nil
          for friendship in friendships
            friends.push(friendship.user2_id)
          end
        end
        friends.push((User.where(name: session[:user]).first).id)
        @entries = Entry.where('user_id IN (?)',friends)
      else
        @entries = Entry.all
      end
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    if !session[:user]
      redirect_to entries_path, :alert => "You have to log in to create a new entry"
    else
        @entry = Entry.new
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
    if @entry.user.name != session[:user] or @entry.user.role != 0
      redirect_to entries_path, :alert => "You cannot edit another user entry!"
    else
      @entry = Entry.find(params[:id])
    end
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)
    @entry.user = User.find_by name: session[:user]
    @entry.likes = 0

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entries_url, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entries_path, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    if @entry.user.name != session[:user] or @entry.user.role != 0
      redirect_to entries_url, :alert => "You cannot delete another user Entry!"
    else
      @entry.destroy
      respond_to do |format|
        format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def share
    text = @entry.user.name + ": " + @entry.text 
    @entryShared = Entry.create(user: User.where(name: session[:user]).first, text: text, likes: 0)

    respond_to do |format|
      if @entryShared.save
        format.html { redirect_to entries_url, notice: 'Entry was successfully shared.' }
        format.json { render :show, status: :created, location: @entryShared }
      else
        format.html { render :new }
        format.json { render json: @entryShared.errors, status: :unprocessable_entity }
      end
    end
  end

  def like
    @entry.likes = @entry.likes + 1
    if @entry.save
        redirect_to entries_url, notice: 'Like registered' 
    else
      render :new         
    end
  end 

  def unlike
    if @entry.likes > 0 
      @entry.likes = @entry.likes - 1
      if @entry.save
        redirect_to entries_url, notice: 'Unlike registered' 
      else
        render :new         
    end
    else
      redirect_to entries_url, notice: 'You can not unlike a 0 like entry' 
    end
  end 
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:text, :user_id, :likes)
    end
  end

mysoapp/app/helpers/entries_helper.rb
module EntriesHelper
end

mysoapp/app/views/entries/_form.html.erb
<%= form_for(entry) do |f| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <!-- <div class="field">
<%= f.label :user_id %><br>
<%= f.text_field :user_id %>
</div> -->

  <!--div class="field">
    <%= f.label :likes %>
    <%= f.number_field :likes %>
  </div-->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mysoapp/app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

mysoapp/app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table>
  <thead>
    <tr>
    <% if session[:user] != nil %>
      <th>Text</th>
      <th>User</th>
      <th>Likes</th>
      <th colspan="3"></th>
    <% else %>
      <th>LOG IN to see your friends entries</th>
    <% end %>
    </tr>
  </thead>

  <tbody>
    <% if session[:user] != nil %>
      <% @entries.each do |entry| %>
        <tr>
          <td><%= entry.text %></td>
          <td><%= entry.user.name %></td>
          <td><%= entry.likes %></td>
          <td><%= link_to 'Show', entry %></td>
          <td><%= link_to 'Share', share_path(entry.id) %></td>
          <td><%= link_to 'Like', like_path(entry.id) %></td>
          <td><%= link_to 'Unlike', unlike_path(entry.id) %></td>
          <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
          <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

mysoapp/app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

mysoapp/app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @entry.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @entry.user.name %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @entry.likes %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>